import type { KnowledgeReport } from '@/types';

interface PdfGeneratorOptions {
  includeMetadata?: boolean;
  customBranding?: {
    logoUrl?: string;
    primaryColor?: string;
  };
}

export class PdfGenerator {
  private options: PdfGeneratorOptions;

  constructor(options: PdfGeneratorOptions = {}) {
    this.options = options;
  }

  async generate(report: KnowledgeReport, videoTitle: string): Promise<Buffer> {
    // In production, this would use Puppeteer or @react-pdf/renderer
    // For now, return a mock PDF buffer
    const html = this.generateHtml(report, videoTitle);
    return Buffer.from(html, 'utf-8');
  }

  private generateHtml(report: KnowledgeReport, videoTitle: string): string {
    const primaryColor = this.options.customBranding?.primaryColor || '#6366f1';

    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${videoTitle} - Knowledge Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
    h1 { color: ${primaryColor}; }
    h2 { color: #1a1a1a; border-bottom: 2px solid ${primaryColor}; padding-bottom: 5px; }
    .meta { color: #666; margin-bottom: 20px; }
    .section { margin-bottom: 25px; }
    .concept { margin-bottom: 15px; padding: 10px; background: #f5f5f5; }
    .step { margin-bottom: 15px; }
    .step-number { display: inline-block; width: 25px; height: 25px; background: ${primaryColor}; color: white; text-align: center; line-height: 25px; border-radius: 50%; margin-right: 10px; }
    .tool { margin-bottom: 10px; padding: 10px; background: #f5f5f5; }
    .required { color: #dc2626; font-size: 12px; }
  </style>
</head>
<body>
  <h1>${videoTitle}</h1>
  <p class="meta">Difficulty: ${report.difficulty_level} | Time: ${report.estimated_time_hours || 'N/A'} hours</p>
  
  <div class="section">
    <h2>Summary</h2>
    <p>${report.summary}</p>
  </div>

  <div class="section">
    <h2>Key Concepts</h2>
    ${report.key_concepts.map(c => `
      <div class="concept">
        <strong>${c.title}</strong> <span class="required">(${c.importance})</span>
        <p>${c.description}</p>
      </div>
    `).join('')}
  </div>

  <div class="section">
    <h2>Implementation Steps</h2>
    ${report.implementation_steps.map(s => `
      <div class="step">
        <span class="step-number">${s.step}</span>
        <strong>${s.title}</strong>
        <p>${s.description}</p>
        <p><em>Expected: ${s.expected_outcome}</em></p>
      </div>
    `).join('')}
  </div>

  <div class="section">
    <h2>Required Tools</h2>
    ${report.tools_list.map(t => `
      <div class="tool">
        <strong>${t.name}</strong> ${t.required ? '<span class="required">(Required)</span>' : ''}
        <p>${t.description}</p>
        ${t.url ? `<p><a href="${t.url}">${t.url}</a></p>` : ''}
      </div>
    `).join('')}
  </div>

  ${this.options.includeMetadata ? `
  <div class="section">
    <h2>Metadata</h2>
    <p>Generated by VidKnow</p>
  </div>
  ` : ''}
</body>
</html>
    `.trim();
  }
}